boleto-api-caixa : envia boleto rules para boleto-api
pagarme/superbowleto pull request #364
Opened 2021-05-14 22:00 UTC by leojasmim

Esta modificação tem por objetivo remover a funcionalidade que força a virada para emissor Bradesco caso o cliente envie o nó `boleto_rules` ou se o mesmo tiver configurado na company a `issuer_wallet = 26`. A virada para o Bradesco era necessária porque a BoletoAPI não aceitava regras menos restritivas de pagamento (baixa em D+n e pagamento divergente do valor do título). Com a implementação da v2 na BoletoAPI, a mesma passará a receber tais informações e a virada para o Bradesco deixará de ser obrigatória.

relates to : [BPROC-98](https://mundipagg.atlassian.net/browse/BPROC-98)

2021-08-30 18:09 UTC, wesleycosta submitted a review, later dismissed

2021-09-01 18:27 UTC, vannessasoares commented on .circleci/config.yml
>  version: 2
```suggestion
version: 2.1
```

2021-09-03 14:33 UTC, VictorSamp approved these changes

2021-09-03 15:28 UTC, vannessasoares requested changes

2021-09-03 15:28 UTC, vannessasoares commented on .circleci/config.yml
> +            aws ecr get-login-password | docker login --username AWS --password-stdin "$STG_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-sdx"
```suggestion
            aws ecr get-login-password | docker login --username AWS --password-stdin "$SDX_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-sdx"
```

2021-09-03 15:28 UTC, vannessasoares commented on .circleci/config.yml
> +            aws ecr get-login-password | docker login --username AWS --password-stdin "$STG_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-prd"
```suggestion
            aws ecr get-login-password | docker login --username AWS --password-stdin "$PRD_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-prd"
```

2021-09-03 16:56 UTC, leojasmim commented on .circleci/config.yml
> +            aws ecr get-login-password | docker login --username AWS --password-stdin "$STG_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-prd"
👌

2021-09-03 16:57 UTC, leojasmim commented on .circleci/config.yml
> +            aws ecr get-login-password | docker login --username AWS --password-stdin "$STG_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-sdx"
👌

2021-09-03 17:41 UTC, vpecanha approved these changes

2021-09-03 17:46 UTC, vannessasoares approved these changes

2021-09-10 18:23 UTC, wesleycosta approved these changes

2021-09-15 20:55 UTC, merged