[BPROC-400] - Adição de campo sacador avalista no request da caixa da superbowleto para a boleto-api
pagarme/superbowleto pull request #371
Opened 2022-03-15 13:26 UTC by davidsmedeiros

## Description

Após adição do campo sacador avalista no request da boleto-api, o campo do sacador avalista deve ser adicionado no request da superbowleto para a boleto-api

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2022-03-15 13:34 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 29a2e51d57b9f6dc2f4bbc14febef64585cb292b
  * Commits must be in the following format: **%{scope}: %{description}**

Check out our Git Style Guide here: https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2022-03-15 15:09 UTC, brunoglm reviewed
opa, @davidsmedeiros , faltou colocar a mensagem do commit com scopo 😀 exemplo `Added field PayeeGuarantor on CEF request`

2022-03-15 15:30 UTC, brunoglm commented on src/providers/boleto-api-caixa/formatter.js
> +const getDocumentType = (documentNumber) => {
opa, @davidsmedeiros senti falta de testes de unidade em cima dessa função `getDocumentType` 😀

2022-03-15 15:42 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +      name: 'Pagar.me Pagamentos S/A',
opa, vale criar uma const exemplo `recipientName `contendo o valor `Pagar.me Pagamentos S/A`, igual foi feito com as const's recipientDocumentType e recipientDocumentNumber 😀

2022-03-15 15:45 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +        type: getDocumentType(path(['company_document_number'], boleto)),
opa, visto que o campo `company_document_number` não é obrigatório na super boleto, vale usarmos o pathOr

```suggestion
        type: getDocumentType(pathOr('',['company_document_number'], boleto)),
```

2022-03-15 15:46 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +        number: path(['company_document_number'], boleto),
opa, visto que o campo company_document_number não é obrigatório na super boleto, vale usarmos o pathOr

```suggestion
        number: pathOr('',['company_document_number'], boleto),
```

2022-03-15 15:48 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +      name: path(['company_name'], boleto),
Podemos usar também a const companyName da linha 88 @davidsmedeiros 😀

2022-03-15 15:50 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +        number: path(['company_document_number'], boleto),
como estamos pegando o nó `company_document_number `duas vezes de boleto, podemos pegar uma vez só, igual o `companyName `da linha 88, e usar para os atributos do `payeeGuarantor` 😀

2022-03-15 15:52 UTC, brunoglm commented on test/unit/providers/boleto-api-caixa/index.js
> +      name: `${boleto.company_name}`,
opa, aqui como não estamos concatenando ou montando uma string dinâmica, podemos passar a variável direto 😀 

```suggestion
      name: 'boleto.company_name',
```

2022-03-15 15:59 UTC, brunoglm reviewed
Deixei algumas sugestões @davidsmedeiros 😀

2022-03-15 20:27 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/formatter.js
> +const getDocumentType = (documentNumber) => {
feito

2022-03-15 20:31 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/index.js
> +      name: 'Pagar.me Pagamentos S/A',
feito

2022-03-15 20:39 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/index.js
> +      name: path(['company_name'], boleto),
feito

2022-03-15 20:42 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/index.js
> +        type: getDocumentType(path(['company_document_number'], boleto)),
feito

2022-03-15 20:42 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/index.js
> +        number: path(['company_document_number'], boleto),
feito

2022-03-15 20:44 UTC, davidsmedeiros commented on test/unit/providers/boleto-api-caixa/index.js
> +      name: `${boleto.company_name}`,
feito

2022-03-16 13:05 UTC, VictorSamp approved these changes

2022-03-16 13:51 UTC, leojasmim approved these changes
@davidsmedeiros @brunoglm Com relação à não obrigatoriedade dos dados de company, do ponto de vista de negócio não deveria haver requisição sem essa informação, dado que não há como transacionar sem company. Talvez uma abordagem seja utilizar as infos do próprio PagarMe na ausência de tais dados, entretanto não acredito que esse cenário ocorra.

2022-03-16 17:20 UTC, cersouza requested changes

2022-03-16 17:20 UTC, cersouza commented on src/providers/boleto-api-caixa/formatter.js
> +  }
@davidsmedeiros, nesse caso, há alguma possibilidade de que `documentNumber` venha `null` ou `undefined`?
1. Se sim, o ideal seria validar antes de pegar o tamanho da variável. Pois se o valor dela for `undefined` o resultado seria `String(undefined).trim().length == 9`
2. Se não, essa validação poderia ser retirada, o que acha?

2022-03-16 17:29 UTC, brunoglm commented on src/providers/boleto-api-caixa/formatter.js
> +  }
@cersouza , se for undefined/null, o `propOr` usado antes de chamar essa função vai setar o valor default(dados da pagarme)

2022-03-16 19:43 UTC, davidsmedeiros commented on src/providers/boleto-api-caixa/formatter.js
> +  }
Foi definido que os dados para undefined/null/vazio será vazio e não mais do pagarme. Também concordo que o if deveria estar no início.

2022-03-16 20:37 UTC, cersouza approved these changes
Boa @davidsmedeiros 🌴

2022-03-17 12:13 UTC, leojasmim submitted a review, later dismissed

2022-03-17 12:32 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +      name: recipientDocumentName,
esse cara seria `recipientName`, não ? 😀

2022-03-17 12:32 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +  instructions += ` A emissão deste boleto foi solicitada e/ou intermediada pela empresa ${companyName} - CNPJ: ${companyDocument}. Para confirmar a existência deste boleto consulte em pagar.me/bolet
Nessa instrução default, deve aparecer dados da pagar.me ou da company ? 😀

2022-03-17 12:34 UTC, brunoglm commented on test/unit/providers/boleto-api-caixa/formatter.js
> +  const result = getDocumentType(documentNumber)
@davidsmedeiros , seria legal testar o cenário de quando o documento é CNPJ e quando passamos uma variavel empty('') 😀

2022-03-18 17:56 UTC, brunoglm submitted a review, later dismissed

2022-03-21 11:10 UTC, leojasmim commented on src/providers/boleto-api-caixa/index.js
> +  instructions += ` A emissão deste boleto foi solicitada e/ou intermediada pela empresa ${companyName} - CNPJ: ${companyDocument}. Para confirmar a existência deste boleto consulte em pagar.me/bolet
@brunoglm Da Company

2022-03-21 11:11 UTC, leojasmim approved these changes

2022-03-21 13:04 UTC, VictorSamp approved these changes

2022-03-23 13:07 UTC, leojasmim approved these changes

2022-03-24 12:54 UTC, merged