[BPROC418]-Remove buyer address when address is equal to pagarme or company
pagarme/superbowleto pull request #375
Opened 2022-03-31 20:54 UTC by davidsmedeiros

## Description

Este PR remove o campo endereço do buyer no request para a boleto-api quando o endereço é substituído pelo endereço do pagarme ou for o mesmo da company.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2022-03-31 20:54 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 5c2f64bd7b38cf2084400fe4ee6f7ffdda3239e8
  * Commits must be in the following format: **%{scope}: %{description}**

Check out our Git Style Guide here: https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2022-03-31 21:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 39429127e8d2d446da3ee36f548286affced4778
  * Commits must be in the following format: **%{scope}: %{description}**

Check out our Git Style Guide here: https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2022-04-01 12:04 UTC, leojasmim approved these changes

2022-04-01 16:56 UTC, cersouza requested changes

2022-04-01 16:56 UTC, cersouza commented on test/unit/providers/boleto-api-caixa/index.js
> +test('payer_address is different than company_address and pagarme address', async (t) => {
Uma sugestão @davidsmedeiros, colocar no nome do teste o que esperado de retorno. Ex: "When payer_address is different than... **then should**...".

2022-04-01 16:56 UTC, cersouza commented on test/unit/providers/boleto-api-caixa/index.js
> +test('payer_address is equals than company_address', async (t) => {
Uma sugestão @davidsmedeiros, colocar no nome do teste o que esperado de retorno. Ex: "When payer_address is different than... **then should**...".

2022-04-01 16:56 UTC, cersouza commented on test/unit/providers/boleto-api-caixa/index.js
> +test('payer_address is equals than address pagarme', async (t) => {
Uma sugestão @davidsmedeiros, colocar no nome do teste o que esperado de retorno. Ex: "When payer_address is different than... **then should**...".

2022-04-04 12:42 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +const buyerAdressIsEqualsToPagarme = (boleto) => {
opa, @davidsmedeiros aqui da para retornarmos direto o resultado 😀 


```suggestion
const buyerAdressIsEqualsToPagarme = (boleto) => {
```
```suggestion
const buyerAdressIsEqualsToPagarme = (boleto) => (equals(boleto.payer_address, boleto.company_address))
```

2022-04-04 12:42 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +const buyerAdressIsEqualsToPagarme = (boleto) => {
opa, @davidsmedeiros aqui da para retornarmos direto o resultado 😀 


```suggestion
const buyerAdressIsEqualsToPagarme = (boleto) => {
```
```suggestion
const buyerAdressIsEqualsToPagarme = (boleto) => (equals(boleto.payer_address, boleto.company_address))
```

2022-04-04 12:43 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +const buyerAdressIsEqualsToAdressCompany = (boleto) => {
opa, aqui também da para retornarmos direto igual a sugestão acima 😀

2022-04-04 12:44 UTC, brunoglm commented on test/unit/providers/boleto-api-caixa/index.js
> +  boleto.payer_address = {
opa, aqui da para passar o objeto direto no método `createBoleto` , igual feito nos testes abaixo 😀

2022-04-04 12:44 UTC, brunoglm commented on test/unit/providers/boleto-api-caixa/index.js
> +  boleto.payer_address = {
opa, aqui da para passar o objeto direto no método `createBoleto` , igual feito nos testes abaixo 😀

2022-04-04 17:22 UTC, cersouza approved these changes
Boaa @davidsmedeiros 💥

2022-04-04 18:03 UTC, brunoglm approved these changes

2022-04-05 14:15 UTC, merged