[BPROC-531] Removes async billet on caixa provider
pagarme/superbowleto pull request #378
Opened 2022-08-02 20:53 UTC by JeanCigoli

## Descrição

Verificamos que em alguns casos de exceção na resposta da BoletoAPI para a Superbowleto o fluxo async é acionado, mesmo com a loja tendo o registro async desabilitado. Com isso acabamos mandando o boleto para o fluxo de registro em background e exibindo uma reposta inconsistente para o cliente.

O intuito dessa alteração é remover todo fluxo async do provedor **caixa**, então ao gerar uma exceção será retornado o status `refused`.

## Alterações existentes no PR:

[X] :bug:  Correção de bug;

## Impacto de deploy

Nenhum impacto esperado na aplicação.

## Testes

Foram criados testes de integração que cobrem as alterações realizadas nesse PR, validando os retornos da função de registro do boleto. Além disso todos os demais testes continuaram passando corretamente:

![image](https://user-images.githubusercontent.com/43609958/182467142-2260b5c5-3860-459d-8add-0765a4ba8d03.png)

## Caso necessário, como realizar o rollback deste PR?

Revert do commit do PR.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2022-08-03 13:38 UTC, leojasmim reviewed
@JeanCigoli Deixei uns comentários 😬

2022-08-03 13:38 UTC, leojasmim commented on src/providers/boleto-api-caixa/index.js
> +    issuer_response_code: 'defaultErrorCode',
@JeanCigoli Na grande maioria dos cenário as resposta da BoletoAPI para um erro inespecífico éo StatusCode 500 com o payload da seguinte forma: 

`{
    "errors": [
        {
            "code": "MP500",
            "message": "Internal error"
        }
    ]
}`

Acho que seria interessante o **issuer_response_code**  e a mensagem ter os valores retornados na mensagem da BoletoAPI de forma simular ao **defaultBoletoApiError** na linha 302. Isso pode ajudar a entender o problema diretamente nos logs da superbowleto ao invés de termos que olhar o logs da BoletoAPI para verificar o problema. Só utilizaria o **defaultErrorValue** caso não a BoletoAPI envie uma resposta de erro que não obedeça o contrato acima e, para esses casos, acho que vale colocar no **issuer_response_code** o statusCode retornado no HTTP. O que acha?

2022-08-03 13:39 UTC, leojasmim commented on test/integration/providers/boleto-api-caixa/index.js
> +import test from 'ava'
@JeanCigoli Muito legal os testes ✅ 🚀

2022-08-03 20:56 UTC, brunoglm commented on src/providers/boleto-api-caixa/index.js
> +      return Promise.resolve(translated)
opa, daria pra usar o __finaly__ e dai teria somente um __return Promise.resolve__ , o que acha ? 😀

2022-08-04 13:06 UTC, JeanCigoli commented on test/integration/providers/boleto-api-caixa/index.js
> +import test from 'ava'
Obrigado!

2022-08-04 13:24 UTC, JeanCigoli commented on src/providers/boleto-api-caixa/index.js
> +      return Promise.resolve(translated)
Testando utilizando o finally, o eslint reclama indicando que a variável pode ser nula no retorno. Então para esse caso preferi manter os retornos isolados dentro do try e do catch

2022-08-04 13:49 UTC, cersouza commented on test/integration/providers/boleto-api-caixa/index.js
> +import test from 'ava'
Realmente @JeanCigoli, fez os testes validando praticamente todos os cenários, muito bom cara 🚀🎺

2022-08-04 14:13 UTC, cersouza requested changes
Boa mr @JeanCigoli até aqui, cara pra quem "não manjava muito de testes", se saiu muito bem 🧪 🎺

2022-08-04 14:13 UTC, cersouza commented on test/integration/providers/boleto-api-caixa/index.js
> +test('register: when the register function not received the billet', async (t) => {
Mano @JeanCigoli, aqui tenho duas sugestões 🙂:
 1 - Ao descrever nomes de cenário de teste, tente sempre descrever o contexto que está sendo testado ao invés dos métodos que são chamados, ex:
 ```js
test('register: when boleto is null')
```
2 - Mesmo que está descrito no código, sugiro colocar no título do teste o resultado esperado, assim não é cenário ler todo o código do teste para entender o que ele testa e espera. Exemplo:
```js
test('register: when boleto is null then should be returned status "refused" and default message error and code')
```

2022-08-04 14:13 UTC, cersouza commented on test/integration/providers/boleto-api-caixa/index.js
> +test('register: when the sendRequestToBoletoApi function return a not mapped error', async (t) => {
Mano @JeanCigoli, aqui tenho duas sugestões 🙂:
 1 - Ao descrever nomes de cenário de teste, tente sempre descrever o contexto que está sendo testado ao invés dos métodos que são chamados, ex:
 ```js
test('register: when BoletoAPI returns a not mapped error')
```
2 - Mesmo que está descrito no código, sugiro colocar no título do teste o resultado esperado, assim não é cenário ler todo o código do teste para entender o que ele testa e espera. Exemplo:
```js
test('register: register: when BoletoAPI returns a not mapped error then should be returned status "refused" and default message error and code')
```

2022-08-04 14:13 UTC, cersouza commented on test/integration/providers/boleto-api-caixa/index.js
> +test('register: when the sendRequestToBoletoApi function return success', async (t) => {
@JeanCigoli, se possível, aplicar a mesmas sugestões dos comentários anteriores 🙂

Sugestão de nome:
```js
test('register: when BoletoAPI returs success response...')
```

2022-08-04 14:22 UTC, JeanCigoli commented on src/providers/boleto-api-caixa/index.js
> +    issuer_response_code: 'defaultErrorCode',
@leojasmim  Concordo! Realizei as mudanças para contemplar as alterações indicadas, agora será retornado o erro corretamente, e somente quando não tiver uma mensagem que será colocada a default. Pode validar novamente?

2022-08-04 14:30 UTC, JeanCigoli commented on test/integration/providers/boleto-api-caixa/index.js
> +import test from 'ava'
Foram dois pontos:

- Como essa parte testa a integração de algumas funções dentro do método register, preferi deixar como de integração.
- E também vi que o teste da função register do bradesco está dentro dessa pasta.

Recomenda colocar em outro lugar @cersouza ?

2022-08-04 16:28 UTC, cersouza commented on test/integration/providers/boleto-api-caixa/index.js
> +import test from 'ava'
Bom ponto @JeanCigoli, em alguns momentos será um pouco filosófico essa decisão, mas concordo contigo!

2022-08-04 16:50 UTC, leojasmim submitted a review, later dismissed

2022-08-04 18:24 UTC, cersouza submitted a review, later dismissed
🎺

2022-08-08 12:48 UTC, brunoglm submitted a review, later dismissed

2022-08-10 15:10 UTC, brunoglm submitted a review, later dismissed

2022-08-11 15:02 UTC, merged