[BPROC-321
pagarme/superbowleto pull request #386
Opened 2022-10-14 15:02 UTC by lucasarantespagarme

## Description

Write a brief and explicative description of your pull request.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2022-10-14 16:27 UTC, davidsmedeiros requested changes

2022-10-14 16:27 UTC, davidsmedeiros commented on src/resources/boleto/schema.js
> +    .when('issuer', { is: 'bradesco', then: Joi.string().replace(/︎/g, '').regex(/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/).normalize('NFKC') })
Acho que vale fazer um teste que verifica a parte is: 'bradesco'. Acho que existe algum teste já feito que o banco é passado. Daí seria validar se, quando um banco diferente do bradesco, no caso a caixa, for passado, a sanitização falha. Além disso, o inverso do teste, quando o banco for Bradesco, sanitiza.

2022-10-14 16:54 UTC, lucasarantespagarme commented on src/resources/boleto/schema.js
> +    .when('issuer', { is: 'bradesco', then: Joi.string().replace(/︎/g, '').regex(/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/).normalize('NFKC') })
valeu @davidsmedeiros , vou fazer o teste !

2022-10-17 12:53 UTC, brunoglm commented on src/resources/boleto/schema.js
> +    .when('issuer', { is: 'bradesco', then: Joi.string().replace(/︎/g, '').regex(/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/).normalize('NFKC') })
opa, @lucasarantespagarme , talvez é bacana colocar o valor __/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/__ em uma const, que com o nome dela explique a regex. Dessa forma um dev olha o nome da const e já sabe o objetivo da regex 😀

2022-10-17 12:55 UTC, brunoglm commented on test/unit/resources/boleto/schema.js
> +const schema = {
opa, @lucasarantespagarme , no teste, temos que usar o __Schema__ oficial que é usado na aplicação. Dessa forma se alguém alterar o schema oficial, o teste não quebra, pois ele está criando seu próprio schema 😀

2022-10-17 13:34 UTC, brunoglm commented on src/resources/boleto/schema.js
> +    .when('issuer', { is: 'bradesco', then: Joi.string().replace(/︎/g, '').regex(/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/).normalize('NFKC') })
@lucasarantespagarme , olhando melhor a regex, me parece que está duplicado o __/d__ e __0-9__ sendo a mesma coisa 😀

2022-10-17 13:36 UTC, brunoglm commented on test/unit/resources/boleto/schema.js
> +import test from 'ava'
Opa, seria bacana um teste passando os caracteres __a-zÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9__ , no qual vai garantir que esses caracteres não causam badRequest 😀

2022-10-17 13:53 UTC, brunoglm commented on test/unit/resources/boleto/schema.js
> +import test from 'ava'
Senti falta dos testes de falha onde volta badRequest, passando um caracter incorreto, por exemplo 😀

2022-10-17 13:56 UTC, brunoglm commented on src/resources/boleto/schema.js
> +    .when('issuer', { is: 'bradesco', then: Joi.string().replace(/︎/g, '').regex(/[a-zA-Z\d\sÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕáéíóúàèìòùâêîôûãõç0-9]*$/).normalize('NFKC') })
opa, duas dúvidas @lucasarantespagarme 

1 - O normalize não deveria vir antes do regex ? que dai se o normalize não resolver, o regex deve bloquear, e voltar badRequests
2 - Olhando a [doc](https://joi.dev/api/?v=15.1.1#stringregexpattern-name--options), com uma versão mais próxima da que estamos usando, reparei que o regex funciona com negação, onde tu passa o __^seu-padrão__ , e dai o que não der match, ele volta badRequests, vale dar uma conferida e testar esse ponto 😀

2022-10-17 15:44 UTC, lucasarantespagarme commented on test/unit/resources/boleto/schema.js
> +import test from 'ava'
boa, vou fazer

2022-10-17 15:44 UTC, lucasarantespagarme commented on test/unit/resources/boleto/schema.js
> +const schema = {
show ! @brunoglm

2022-10-18 12:32 UTC, kayquecoelho submitted a review, later dismissed

2022-10-18 13:19 UTC, brunoglm submitted a review, later dismissed

2022-10-18 13:50 UTC, brunoglm approved these changes

2022-10-18 14:16 UTC, ramonpaolo approved these changes

2022-10-18 14:37 UTC, JeanCigoli approved these changes

2022-10-19 19:23 UTC, davidsmedeiros approved these changes

2022-10-19 20:40 UTC, merged