[BPROC-860] Adicionar catalog-info para o backstage
pagarme/superbowleto pull request #390
Opened 2022-12-20 14:43 UTC by kayquecoelho

## Description

### Tarefa [BPROC-860](https://mundipagg.atlassian.net/browse/BPROC-860)

Esse PR tem como intuito adicionar as informações do sistema da superbowleto no BackStage, definindo seus componentes e recursos, bem como dependências.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
2. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
3. My changes are well covered by **tests** and **logs**
4. I've updated the project docs (if needed)
5. I fell safe about this implementation
6. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2022-12-21 18:24 UTC, brunoglm commented on catalog-info.yaml
> +  dependsOn:
opa, na Doc só tem esse atributo no **kind Resource** 😀

2022-12-21 18:30 UTC, brunoglm approved these changes

2022-12-22 12:58 UTC, cersouza requested changes
Boa mano @kayquecoelho, até aqui. Deixei alguns comentários 🙂

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/ci: circleci
Mano @kayquecoelho, agora nosso processo de CI da Superbowleto está sendo através do `github-actions`  🙂

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/ci: circleci
Mano @kayquecoelho, agora nosso processo de CI da Superbowleto está sendo através do `github-actions`  🙂

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    - resource:pagarme/live-superbowleto
Boa mano @kayquecoelho, acho que dá para colocar que depende também da `boleto-api`. Será que vale a pena ? 🤔

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/ci: circleci
Mano @kayquecoelho, agora nosso processo de CI da Superbowleto está sendo através do `github-actions`  🙂

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +  dependsOn:
Boa mano @kayquecoelho, acho que dá para colocar que depende também da `boleto-api`. Será que vale a pena ? 🤔

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/cd: circleci
Nesse caso @kayquecoelho , acredito que não temos CI/CD para SQS, então poderia remover.

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +  type: repository
Mano @kayquecoelho, acho que o type poderia ser `backend`, `repository` é para declara o repo do projeto

2022-12-22 12:58 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/cd: circleci
Nesse caso @kayquecoelho , acredito que não temos CI/CD para o Repo, então poderia remover.

2022-12-27 19:56 UTC, JeanCigoli submitted a review, later dismissed

2022-12-29 18:59 UTC, brunoglm submitted a review, later dismissed

2022-12-30 13:59 UTC, cersouza submitted a review, later dismissed

2022-12-30 17:30 UTC, cersouza approved these changes

2022-12-30 17:30 UTC, brunoglm approved these changes

2022-12-30 17:39 UTC, merged