chore: add stg workflow
pagarme/superbowleto pull request #391
Opened 2023-02-10 17:18 UTC by leojasmim

## Description

Write a brief and explicative description of your pull request.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

2023-02-23 13:25 UTC, brunoglm commented on .circleci/config.yml
> +#  push_stg:
@leojasmim , esses caras como comentário, precisam estar no arquivo mesmo ? 😀

2023-02-23 13:26 UTC, brunoglm commented on .circleci/config.yml
> +#  push_stg:
@leojasmim , talvez é uma boa remover esses caras que não rodam mais 😀

2023-02-23 14:00 UTC, leojasmim commented on .circleci/config.yml
> +#  push_stg:
> @leojasmim , talvez é uma boa remover esses caras que não rodam mais 😀

@brunoglm Feito

2023-02-23 14:13 UTC, JeanCigoli submitted a review, later dismissed

2023-02-23 14:34 UTC, lucasarantespagarme submitted a review, later dismissed

2023-02-23 14:50 UTC, brunoglm approved these changes

2023-02-23 16:38 UTC, btfshadow requested changes

2023-02-23 16:38 UTC, btfshadow commented on .github/workflows/superbowleto_deploy.yml
> +    runs-on: ubuntu-latest
tem algum motivo para não estar usando o small-runner aqui ?

2023-02-23 16:38 UTC, btfshadow commented on .github/workflows/superbowleto_build_and_push.yml
> +    runs-on: ubuntu-latest
tem algum motivo para não estar usando o small-runner aqui ?

2023-02-23 16:38 UTC, btfshadow commented on .github/workflows/build_and_deploy_sdx.yml
> +      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
Precisa de uma linha no final do arquivo

2023-02-23 16:38 UTC, btfshadow commented on .github/workflows/build_and_deploy_prd.yml
> +      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
Precisa de uma linha no final do arquivo

2023-02-23 16:41 UTC, cersouza commented on .github/workflows/superbowleto_build_and_push.yml
> +    runs-on: ubuntu-latest
@btfshadow, acredito que seja por o repositório ser púplico o projeto não conseguiu ter acesso ao servidor self-hosted, conforme o comentário da linha 70.

2023-02-23 16:44 UTC, cersouza commented on .github/workflows/superbowleto_build_and_push.yml
> +    runs-on: ubuntu-latest
Eu sugeria deixar uma versão de Ubuntu Fixa, para não ter perigo de lançarem alguma mudança que quebre o pipeline. Será que faz sentido ?

2023-02-23 16:45 UTC, cersouza approved these changes

2023-02-23 16:46 UTC, leojasmim commented on .github/workflows/superbowleto_deploy.yml
> +    runs-on: ubuntu-latest
@btfshadow Pelo que entendi não dá para utilizar máquinas `self-hosted` em projetos abertos.

2023-02-23 16:58 UTC, btfshadow approved these changes

2023-02-23 16:58 UTC, btfshadow commented on .github/workflows/superbowleto_deploy.yml
> +    runs-on: ubuntu-latest
verdade erro meu

2023-02-23 16:58 UTC, btfshadow commented on .github/workflows/superbowleto_build_and_push.yml
> +    runs-on: ubuntu-latest
verdade erro meu

2023-02-24 13:57 UTC, cersouza approved these changes

2023-02-24 18:19 UTC, brunoglm approved these changes

2023-03-09 13:31 UTC, merged